'use client';
import {useEffect,useState} from 'react';

type Status='Improving'|'Plateau'|'Declining'|'No data';
type Client={name:string;initials:string;status:Status;score:number;note:string;strength:string;volume:string;adherence:string;planned:number;done:number;program:string};
type Exercise={name:string;icon:string;sets:number;reps:string;kg:number;rest:number};
type Program={id:number;name:string;days:number;clients:number;exercises:Exercise[]};
type View='landing'|'pt-home'|'clients'|'client'|'programs'|'program-editor'|'athlete-home'|'calendar'|'sheet'|'picker'|'workout'|'progress'|'summary';

const baseExercises:Exercise[]=[
 {name:'Lat machine',icon:'↧',sets:3,reps:'8–10',kg:55,rest:90},{name:'Chest press',icon:'↔',sets:3,reps:'8–10',kg:60,rest:90},
 {name:'Military press',icon:'↑',sets:3,reps:'8',kg:35,rest:90},{name:'Squat',icon:'⌄',sets:3,reps:'8',kg:80,rest:120},
 {name:'Tricipiti ai cavi',icon:'⇣',sets:3,reps:'12',kg:25,rest:60},{name:'Bicipiti ai cavi',icon:'⌁',sets:3,reps:'12',kg:20,rest:60}
];
const starterPrograms:Program[]=[
 {id:1,name:'Total Body · Base',days:3,clients:8,exercises:baseExercises},{id:2,name:'Ricondizionamento',days:2,clients:4,exercises:baseExercises.slice(0,4)},
 {id:3,name:'Performance 4 giorni',days:4,clients:3,exercises:baseExercises}
];
const starterClients:Client[]=[
 ['Marco Rossi','MR','Plateau',78,'Chest press stabile da 5 settimane','+2,1%','+1,2%','91%',3,2,'Total Body · Base'],
 ['Andrea Bianchi','AB','Declining',61,'Performance −8% negli ultimi 3 workout','−8,0%','−6,0%','68%',3,1,'Total Body · Base'],
 ['Giulia Verdi','GV','Improving',91,'Squat +12% nelle ultime 6 settimane','+12,0%','+15,4%','97%',4,4,'Performance 4 giorni'],
 ['Sara Conti','SC','Improving',86,'3 PR questo mese','+8,7%','+9,1%','94%',3,3,'Total Body · Base'],
 ['Matteo Romano','MR','Improving',83,'Progressione costante','+6,2%','+8,0%','88%',3,2,'Total Body · Base'],
 ['Elena Ricci','ER','Plateau',73,'Volume stabile da 4 settimane','+0,8%','+0,4%','90%',2,2,'Ricondizionamento'],
 ['Lorenzo Gallo','LG','Declining',58,'Ultimo workout 7 giorni fa','−4,2%','−7,1%','61%',3,1,'Total Body · Base'],
 ['Marta Leone','ML','Improving',88,'Stacco +10% in 8 settimane','+9,8%','+11,2%','95%',4,4,'Performance 4 giorni'],
 ['Davide Moretti','DM','No data',0,'In attesa del primo workout','—','—','—',2,0,'Ricondizionamento'],
 ['Anna Ferri','AF','Improving',84,'Ottima regolarità','+5,9%','+7,2%','98%',3,3,'Total Body · Base'],
 ['Paolo Greco','PG','Plateau',71,'Carichi invariati da 3 settimane','+0,3%','+1,0%','82%',3,2,'Total Body · Base'],
 ['Chiara Fontana','CF','Improving',89,'5 PR questo mese','+10,1%','+12,8%','96%',4,4,'Performance 4 giorni']
].map(x=>({name:x[0] as string,initials:x[1] as string,status:x[2] as Status,score:x[3] as number,note:x[4] as string,strength:x[5] as string,volume:x[6] as string,adherence:x[7] as string,planned:x[8] as number,done:x[9] as number,program:x[10] as string}));
const weeks=[
 {date:'19 AGO',done:2,planned:3,volume:'6.820 kg',score:72},{date:'26 AGO',done:3,planned:3,volume:'7.140 kg',score:75},
 {date:'2 SET',done:3,planned:3,volume:'7.510 kg',score:79},{date:'9 SET',done:2,planned:3,volume:'7.840 kg',score:82}
];
const load=<T,>(key:string,fallback:T):T=>{if(typeof window==='undefined')return fallback;try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};

export default function App(){
 const[view,setView]=useState<View>('landing'),[clients,setClients]=useState<Client[]>(()=>load('progressi-clients',starterClients)),[programs,setPrograms]=useState<Program[]>(()=>load('progressi-programs',starterPrograms));
 const[selectedClient,setSelectedClient]=useState(0),[selectedProgram,setSelectedProgram]=useState<Program|null>(null),[filter,setFilter]=useState('Tutti'),[modal,setModal]=useState(false);
 const[weekDays,setWeekDays]=useState(()=>load('progressi-days',['Lunedì','Mercoledì','Venerdì'])),[completed,setCompleted]=useState<number[]>([]),[exercise,setExercise]=useState(0),[setNo,setSetNo]=useState(1),[kg,setKg]=useState(55),[reps,setReps]=useState(9),[seconds,setSeconds]=useState(0),[toast,setToast]=useState('');
 useEffect(()=>{if(seconds<1)return;const timer=setInterval(()=>setSeconds(v=>v-1),1000);return()=>clearInterval(timer)},[seconds]);
 const go=(next:View)=>{setView(next);scrollTo(0,0)};
 const persistClients=(next:Client[])=>{setClients(next);localStorage.setItem('progressi-clients',JSON.stringify(next))};
 const persistPrograms=(next:Program[])=>{setPrograms(next);localStorage.setItem('progressi-programs',JSON.stringify(next))};
 const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(''),2200)};
 const reset=()=>{localStorage.clear();setClients(starterClients);setPrograms(starterPrograms);setWeekDays(['Lunedì','Mercoledì','Venerdì']);setCompleted([]);notify('Demo ripristinata')};
 if(view==='landing')return <Landing go={go}/>;
 if(['athlete-home','calendar','sheet','progress'].includes(view))return <AthleteShell view={view} go={go} reset={reset}>{view==='athlete-home'?<AthleteHome go={go}/>:view==='calendar'?<Calendar days={weekDays} setDays={d=>{setWeekDays(d);localStorage.setItem('progressi-days',JSON.stringify(d))}}/>:view==='sheet'?<AthleteSheet go={go}/>:<Progress/>}</AthleteShell>;
 if(view==='picker')return <Picker completed={completed} choose={i=>{setExercise(i);setSetNo(1);setKg(baseExercises[i].kg);setReps(Number(baseExercises[i].reps.split('–')[0]));go('workout')}} go={go}/>;
 if(view==='workout'){const current=baseExercises[exercise];const finishSet=()=>{if(setNo<3){setSetNo(v=>v+1);setSeconds(current.rest)}else{setCompleted(v=>[...new Set([...v,exercise])]);setSeconds(0);go('picker')}};return <Workout current={current} setNo={setNo} kg={kg} reps={reps} setKg={setKg} setReps={setReps} complete={finishSet} seconds={seconds} skip={()=>setSeconds(0)} go={go}/>}
 if(view==='summary')return <Summary go={go}/>;
 const active=view==='pt-home'?'pt-home':view==='client'?'clients':view;
 return <PtShell active={active} go={go} reset={reset} add={()=>view==='programs'?openProgram():setModal(true)} toast={toast}>
  {view==='pt-home'?<PtHome clients={clients} openGroup={f=>{setFilter(f);go('clients')}} openClient={i=>{setSelectedClient(i);go('client')}}/>:
   view==='clients'?<Clients clients={clients} filter={filter} setFilter={setFilter} open={i=>{setSelectedClient(i);go('client')}} add={()=>setModal(true)}/>:
   view==='client'?<ClientDetail client={clients[selectedClient]} go={go}/>:view==='programs'?<Programs programs={programs} create={openProgram} edit={p=>{setSelectedProgram(p);go('program-editor')}}/>:
   <ProgramEditor initial={selectedProgram} save={p=>{const exists=programs.some(x=>x.id===p.id);persistPrograms(exists?programs.map(x=>x.id===p.id?p:x):[...programs,p]);notify('Scheda salvata nella libreria');go('programs')}} cancel={()=>go('programs')}/>}
  {modal&&<ClientModal programs={programs} close={()=>setModal(false)} save={c=>{persistClients([...clients,c]);setModal(false);notify('Cliente creato e scheda assegnata')}}/>}
 </PtShell>;
 function openProgram(){setSelectedProgram(null);go('program-editor')}
}

function Logo(){return <span className="progressi-logo"><i><b/><b/><b/></i><strong>Progress<span>ì</span></strong></span>}
function Landing({go}:{go:(v:View)=>void}){return <main className="landing"><nav><button className="brand" onClick={()=>go('landing')}><Logo/></button><div className="nav-actions"><button className="quiet" onClick={()=>go('athlete-home')}>Vista atleta</button><button className="nav-cta" onClick={()=>go('pt-home')}>Apri la demo</button></div></nav><section className="hero"><div className="hero-copy"><div className="pill"><i/> Intelligence che porta risultati</div><h1>Progressi chiari.<br/><em>Decisioni migliori.</em></h1><p>Gli atleti registrano ogni serie in pochi secondi. Tu sai chi sta migliorando, chi si è fermato e chi ha bisogno di te.</p><div className="hero-actions"><button className="primary" onClick={()=>go('pt-home')}>Esplora come PT <span>→</span></button><button className="secondary" onClick={()=>go('athlete-home')}>Prova come atleta</button></div></div><DashboardPreview/></section><section className="cycle"><span>Programma</span><i>→</i><span>Allenati</span><i>→</i><span>Registra</span><i>→</i><span>Comprendi</span><i>→</i><strong>Progredisci</strong></section></main>}
function DashboardPreview(){return <div className="product-preview"><div className="window-bar"><b><Logo/></b><span>Panoramica</span><span>Clienti</span><span>Schede</span></div><div className="preview-head"><div><small>BUONGIORNO, LUCA</small><h2>La tua squadra, a colpo d&apos;occhio.</h2></div></div><div className="metric-grid"><div className="metric"><span>CLIENTI</span><strong>12</strong><small>attivi</small></div><div className="metric highlight"><span>IN PROGRESSO</span><strong>58%</strong><small>7 clienti</small></div><div className="metric"><span>ATTENZIONE</span><strong>5</strong><small>plateau o calo</small></div></div><div className="attention">{starterClients.slice(0,3).map(c=><article key={c.name}><i className="avatar">{c.initials}</i><div><strong>{c.name}</strong><small>{c.note}</small></div><StatusPill value={c.status}/></article>)}</div></div>}

function PtShell({active,go,reset,add,toast,children}:{active:string;go:(v:View)=>void;reset:()=>void;add:()=>void;toast:string;children:React.ReactNode}){return <main className="coach-app"><aside><button className="brand" onClick={()=>go('landing')}><Logo/></button><p>SPAZIO COACH</p>{[['pt-home','⌂','Panoramica'],['clients','♙','Clienti'],['programs','▦','Schede']].map(x=><button key={x[0]} className={active===x[0]?'active':''} onClick={()=>go(x[0] as View)}><i>{x[1]}</i>{x[2]}</button>)}<div className="aside-bottom"><button onClick={()=>go('athlete-home')}>⇄ Vista atleta</button><button onClick={reset}>↻ Reset demo</button></div></aside><div className="coach-main"><header><span className="demo-badge">DEMO</span><button className="add-btn" onClick={add}>＋ {active==='programs'?'Nuova scheda':'Aggiungi cliente'}</button><i className="coach-avatar">LB</i></header>{children}</div>{toast&&<div className="toast">✓ {toast}</div>}</main>}
function PtHome({clients,openGroup,openClient}:{clients:Client[];openGroup:(f:string)=>void;openClient:(i:number)=>void}){const counts={Improving:clients.filter(c=>c.status==='Improving').length,Plateau:clients.filter(c=>c.status==='Plateau').length,Declining:clients.filter(c=>c.status==='Declining').length};return <section className="coach-page"><p className="eyebrow">PANORAMICA · QUESTA SETTIMANA</p><h1>Buongiorno, Luca.</h1><p className="lede">Ogni numero è un punto di partenza.</p><div className="coach-metrics clickable"><button onClick={()=>openGroup('Tutti')}><span>CLIENTI</span><b>{clients.length}</b><small>Vedi tutti →</small></button><button className="green" onClick={()=>openGroup('Improving')}><span>IN MIGLIORAMENTO</span><b>{counts.Improving}</b><small>Apri gruppo →</small></button><button onClick={()=>openGroup('Plateau')}><span>PLATEAU</span><b>{counts.Plateau}</b><small>Apri gruppo →</small></button><button className="red" onClick={()=>openGroup('Declining')}><span>IN CALO</span><b>{counts.Declining}</b><small>Apri gruppo →</small></button></div><div className="section-title"><div><h2>Richiedono attenzione</h2><p>Priorità basata su performance e presenza.</p></div></div><div className="attention-list">{clients.filter(c=>c.status==='Plateau'||c.status==='Declining').slice(0,4).map(c=><ClientRow key={c.name} c={c} click={()=>openClient(clients.indexOf(c))}/>)}</div></section>}
function Clients({clients,filter,setFilter,open,add}:{clients:Client[];filter:string;setFilter:(x:string)=>void;open:(i:number)=>void;add:()=>void}){const shown=filter==='Tutti'?clients:clients.filter(c=>c.status===filter);return <section className="coach-page"><div className="program-heading"><div><p className="eyebrow">ATLETI</p><h1>I tuoi clienti</h1><p className="lede">Presenze, programmi e progressi in un solo posto.</p></div><button className="primary" onClick={add}>＋ Aggiungi cliente</button></div><div className="filters">{['Tutti','Improving','Plateau','Declining','No data'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="client-table">{shown.map(c=><ClientRow key={c.name} c={c} click={()=>open(clients.indexOf(c))}/>)}</div></section>}
function ClientRow({c,click}:{c:Client;click:()=>void}){return <button className="client-row" onClick={click}><i className="avatar">{c.initials}</i><div><b>{c.name}</b><small>{c.program}</small><span className="attendance">Settimana: <strong>{c.done} di {c.planned}</strong> giorni</span></div><StatusPill value={c.status}/><div className="row-score"><small>SCORE</small><b>{c.score||'—'}</b></div><strong>→</strong></button>}
function StatusPill({value}:{value:Status}){return <span className={'status '+value.toLowerCase().replace(' ','-')}>{value}</span>}
function ClientDetail({client:c,go}:{client:Client;go:(v:View)=>void}){return <section className="coach-page"><button className="back" onClick={()=>go('clients')}>← Tutti i clienti</button><div className="profile-title"><i className="avatar big">{c.initials}</i><div><h1>{c.name}</h1><StatusPill value={c.status}/></div><button className="secondary" onClick={()=>go('programs')}>Apri scheda →</button></div><div className="client-tabs"><button className="active">Panoramica</button><button onClick={()=>document.getElementById('history')?.scrollIntoView({behavior:'smooth'})}>Storico</button><button onClick={()=>go('programs')}>Scheda</button></div><div className="detail-grid"><div className="detail-main"><div className="client-score"><span>PROGRESS SCORE <small>DEMO</small></span><b>{c.score||'—'}<em>/100</em></b><Spark/></div><div className="trend-cards four"><div><span>FORZA</span><b>{c.strength}</b></div><div><span>VOLUME</span><b>{c.volume}</b></div><div><span>COSTANZA</span><b>{c.adherence}</b></div><div><span>PRESENZE</span><b>{c.done}/{c.planned}</b></div></div><History/></div><aside className="insights"><article className="ai-card"><span>COACH INSIGHT ✨ <small>PREVIEW</small></span><p>“{c.name.split(' ')[0]} mantiene una buona costanza. La chest press è stabile da cinque settimane: valuta volume, intensità e recupero.”</p></article><h3>Segnali</h3><div>⚠️ <span>Chest press in plateau</span></div><div>🔥 <span>Squat in progressione</span></div><div>✓ <span>{c.done} allenamenti completati su {c.planned}</span></div></aside></div></section>}
function History(){return <section id="history" className="history-card"><div className="section-title"><div><h2>Storico completo</h2><p>Ultime 4 settimane</p></div></div>{weeks.map((w,i)=><article key={w.date}><div><b>{w.date}</b><small>Settimana {i+1}</small></div><span><strong>{w.done}/{w.planned}</strong> allenamenti</span><span><strong>{w.volume}</strong> volume</span><span><strong>{w.score}</strong> score</span><Spark/></article>)}</section>}

function Programs({programs,create,edit}:{programs:Program[];create:()=>void;edit:(p:Program)=>void}){return <section className="coach-page"><div className="program-heading"><div><p className="eyebrow">LIBRERIA SCHEDE</p><h1>Programmi riutilizzabili</h1><p className="lede">Crea, modifica e assegna senza ripartire da zero.</p></div><button className="primary" onClick={create}>＋ Nuova scheda</button></div><div className="program-library rich">{programs.map((p,i)=><article key={p.id}><i className="program-icon">{i+1}</i><div><b>{p.name}</b><small>{p.exercises.length} esercizi per giorno · ordine flessibile</small></div><strong>{p.days}× sett.</strong><span>{p.clients} clienti</span><button onClick={()=>edit(p)}>Modifica →</button></article>)}</div><h2 className="templates-title">Template rapidi</h2><div className="templates">{['Full Body 3 giorni','Upper / Lower','Forza essenziale','Ipertrofia base'].map((x,i)=><button key={x} onClick={create}><i>{['FB3','U/L','STR','HYP'][i]}</i><b>{x}</b><span>Usa template →</span></button>)}</div></section>}
function ProgramEditor({initial,save,cancel}:{initial:Program|null;save:(p:Program)=>void;cancel:()=>void}){const[name,setName]=useState(initial?.name||''),[days,setDays]=useState(initial?.days||3),[items,setItems]=useState<Exercise[]>(initial?.exercises||baseExercises),[newName,setNewName]=useState('');const addExercise=()=>{if(!newName.trim())return;setItems([...items,{name:newName,icon:'◆',sets:3,reps:'10',kg:20,rest:90}]);setNewName('')};return <section className="coach-page editor-page"><button className="back" onClick={cancel}>← Libreria schede</button><div className="editor-head"><div><p className="eyebrow">{initial?'MODIFICA SCHEDA':'NUOVA SCHEDA'}</p><h1>{initial?'Aggiorna il programma':'Crea un nuovo programma'}</h1></div><button className="primary" onClick={()=>save({id:initial?.id||Date.now(),name:name||'Scheda senza nome',days,clients:initial?.clients||0,exercises:items})}>Salva scheda</button></div><div className="editor-grid"><div className="editor-main"><label className="big-field">Nome della scheda<input value={name} onChange={e=>setName(e.target.value)} placeholder="es. Total Body · Principianti"/></label><fieldset className="days-field"><legend>Giorni a settimana</legend><div>{[2,3,4,5].map(n=><button type="button" className={days===n?'active':''} onClick={()=>setDays(n)} key={n}>{n} giorni</button>)}</div></fieldset><div className="section-title"><div><h2>Esercizi del giorno</h2><p>Trascina mentalmente l&apos;ordine consigliato; l&apos;atleta potrà comunque scegliere.</p></div></div><div className="exercise-editor">{items.map((x,i)=><article key={i}><i>{i+1}</i><input value={x.name} onChange={e=>setItems(items.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/><label>Serie<input type="number" value={x.sets} onChange={e=>setItems(items.map((v,n)=>n===i?{...v,sets:+e.target.value}:v))}/></label><label>Reps<input value={x.reps} onChange={e=>setItems(items.map((v,n)=>n===i?{...v,reps:e.target.value}:v))}/></label><label>Recupero<input type="number" value={x.rest} onChange={e=>setItems(items.map((v,n)=>n===i?{...v,rest:+e.target.value}:v))}/></label><button onClick={()=>setItems(items.filter((_,n)=>n!==i))}>×</button></article>)}</div><div className="new-exercise"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nome nuovo esercizio"/><button onClick={addExercise}>＋ Crea esercizio</button></div></div><aside className="editor-summary"><span>RIEPILOGO</span><b>{name||'Nuova scheda'}</b><p>{days} giorni a settimana</p><p>{items.length} esercizi per allenamento</p><p>{items.reduce((n,x)=>n+x.sets,0)} serie totali</p></aside></div></section>}
function ClientModal({programs,close,save}:{programs:Program[];close:()=>void;save:(c:Client)=>void}){const[name,setName]=useState(''),[program,setProgram]=useState(programs[0]);return <div className="modal-back"><form className="modal" onSubmit={e=>{e.preventDefault();const bits=name.split(' ');save({name,initials:bits.map(x=>x[0]).join('').slice(0,2).toUpperCase(),status:'No data',score:0,note:'In attesa del primo workout',strength:'—',volume:'—',adherence:'—',planned:program.days,done:0,program:program.name})}}><button type="button" className="modal-close" onClick={close}>×</button><p className="eyebrow">NUOVO CLIENTE</p><h2>Profilo e scheda</h2><label>Nome e cognome<input required value={name} onChange={e=>setName(e.target.value)} placeholder="es. Federico Costa"/></label><label>Email<input type="email" placeholder="federico@email.it"/></label><label>Scheda assegnata<select value={program.id} onChange={e=>setProgram(programs.find(p=>p.id===+e.target.value)||program)}>{programs.map(p=><option value={p.id} key={p.id}>{p.name} · {p.days} giorni</option>)}</select></label><div className="assigned-preview"><span>{program.name}</span><small>{program.days} giorni/settimana · {program.exercises.length} esercizi per giorno</small></div><button className="primary wide">Crea cliente e assegna</button></form></div>}

function AthleteShell({view,go,reset,children}:{view:View;go:(v:View)=>void;reset:()=>void;children:React.ReactNode}){return <main className="athlete-app"><header className="mobile-top"><button className="brand" onClick={()=>go('landing')}><Logo/></button><button className="circle-btn" onClick={reset}>↻</button></header>{children}<nav className="bottom-nav"><button className={view==='athlete-home'?'active':''} onClick={()=>go('athlete-home')}><i>⌂</i>Oggi</button><button className={view==='calendar'?'active':''} onClick={()=>go('calendar')}><i>□</i>Calendario</button><button className={view==='sheet'?'active':''} onClick={()=>go('sheet')}><i>▦</i>Scheda</button><button className={view==='progress'?'active':''} onClick={()=>go('progress')}><i>↗</i>Progressi</button><button onClick={()=>go('pt-home')}><i>⇄</i>PT</button></nav></main>}
function AthleteHome({go}:{go:(v:View)=>void}){return <section className="ath-home"><p className="date">DOMENICA · 7 SETTEMBRE</p><h1>Ciao, Marco <span>👋</span></h1><p className="sub">Il tuo prossimo allenamento è pronto.</p><article className="today-card"><div className="day-mark">2</div><p className="eyebrow">PROGRAMMA · 3 GIORNI</p><h2>Allenamento giorno 2</h2><p>6 esercizi · circa 55 min</p><div className="exercise-line">Ordine consigliato, scelta libera degli esercizi</div><button className="start-btn" onClick={()=>go('picker')}>Apri allenamento <span>→</span></button><small>Questa settimana: 1 di 3 completati</small></article><div className="ath-stats"><div><span>SETTIMANA</span><b>1 / 3</b><small>giorni svolti</small></div><div><span>STREAK</span><b>5</b><small>settimane</small></div><div><span>SCORE</span><b>82</b><small>in crescita</small></div></div><div className="quick-links"><button onClick={()=>go('calendar')}><i>□</i><span><b>Calendario</b><small>Sposta i giorni della settimana</small></span><em>→</em></button><button onClick={()=>go('progress')}><i>↗</i><span><b>Tutti i progressi</b><small>Storico, forza e costanza</small></span><em>→</em></button></div></section>}
function Calendar({days,setDays}:{days:string[];setDays:(x:string[])=>void}){const all=['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];const move=(i:number,val:string)=>{const next=[...days];next[i]=val;setDays(next)};return <section className="ath-home calendar-page"><p className="date">PROGRAMMA SETTIMANALE</p><h1>Il tuo calendario</h1><p className="sub">Scegli quando svolgere ogni allenamento. La sequenza rimane sempre Giorno 1 → 2 → 3.</p><div className="week-strip">{all.map(d=><div className={days.includes(d)?'active':''} key={d}><span>{d.slice(0,3)}</span><b>{days.indexOf(d)+1||'·'}</b></div>)}</div><div className="calendar-list">{days.map((d,i)=><article key={i}><i>{i+1}</i><div><b>Allenamento giorno {i+1}</b><small>{baseExercises.length} esercizi · circa 55 min</small></div><select value={d} onChange={e=>move(i,e.target.value)}>{all.map(x=><option key={x}>{x}</option>)}</select></article>)}</div><p className="form-note">Se salti un giorno, la dashboard del tuo PT mostrerà gli allenamenti svolti rispetto a quelli previsti.</p></section>}
function AthleteSheet({go}:{go:(v:View)=>void}){return <section className="ath-home sheet-page"><p className="date">SCHEDA ATTIVA</p><h1>Total Body · Base</h1><p className="sub">3 giorni a settimana · aggiornata dal tuo PT</p><div className="sheet-days">{[1,2,3].map((d,i)=><article key={d}><div><i>{d}</i><span><b>Allenamento giorno {d}</b><small>{i===0?'Completato':i===1?'Prossimo':'Da fare'}</small></span></div><div className="sheet-exercises">{baseExercises.map((x,n)=><span key={x.name}><i>{x.icon}</i><small>{n+1}. {x.name}</small></span>)}</div>{i===1&&<button className="primary" onClick={()=>go('picker')}>Apri allenamento →</button>}</article>)}</div></section>}
function Picker({completed,choose,go}:{completed:number[];choose:(i:number)=>void;go:(v:View)=>void}){return <main className="athlete-app"><header className="ath-head"><button className="circle-btn" onClick={()=>go('athlete-home')}>←</button><div><small>ALLENAMENTO GIORNO 2</small><b>{completed.length}/6 esercizi</b></div><button className="text-btn" onClick={()=>completed.length===6&&go('summary')}>{completed.length===6?'Termina':'In corso'}</button></header><section className="exercise-picker"><p className="eyebrow">ORDINE CONSIGLIATO · FLESSIBILE</p><h1>Scegli il prossimo esercizio</h1><p>Segui i numeri oppure passa a un altro attrezzo se quello consigliato è occupato.</p><div className="exercise-grid">{baseExercises.map((x,i)=><button className={completed.includes(i)?'done':''} onClick={()=>!completed.includes(i)&&choose(i)} key={x.name}><span className="order-number">{i+1}</span><i>{completed.includes(i)?'✓':x.icon}</i><b>{x.name}</b><small>{completed.includes(i)?'Completato':`${x.sets} × ${x.reps}`}</small></button>)}</div>{completed.length===6&&<button className="primary wide" onClick={()=>go('summary')}>Termina allenamento</button>}</section></main>}
function Workout({current,setNo,kg,reps,setKg,setReps,complete,seconds,skip,go}:{current:Exercise;setNo:number;kg:number;reps:number;setKg:(x:number)=>void;setReps:(x:number)=>void;complete:()=>void;seconds:number;skip:()=>void;go:(v:View)=>void}){return <main className="athlete-app workout-screen"><header className="ath-head"><button className="circle-btn" onClick={()=>go('picker')}>←</button><div><small>ALLENAMENTO GIORNO 2</small><b>Serie {setNo} di {current.sets}</b></div><button className="text-btn" onClick={()=>go('picker')}>Cambia</button></header><section className="set-stage"><div className="exercise-symbol">{current.icon}</div><h1>{current.name}</h1><p>Target · {current.sets} × {current.reps}</p><div className="set-dots">{[1,2,3].map(n=><i className={n<setNo?'checked':n===setNo?'active':''} key={n}>{n<setNo?'✓':n}</i>)}</div><div className="last-time"><span>ULTIMA VOLTA</span><b>{current.kg} kg × {current.reps}</b></div><div className="steppers"><Stepper label="CARICO" value={kg} unit="kg" step={2.5} set={setKg}/><Stepper label="RIPETIZIONI" value={reps} unit="reps" step={1} set={setReps}/></div><button className="complete-btn" onClick={complete}>✓ Serie completata</button></section>{seconds>0&&<div className="timer"><div><span>RECUPERO</span><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong></div><button onClick={skip}>Salta</button></div>}</main>}
function Stepper({label,value,unit,step,set}:{label:string;value:number;unit:string;step:number;set:(x:number)=>void}){return <div className="stepper"><span>{label}</span><div><button onClick={()=>set(Math.max(0,value-step))}>−</button><b>{value}<small>{unit}</small></b><button onClick={()=>set(value+step)}>+</button></div></div>}
function Progress(){return <section className="ath-home progress-page"><p className="date">STORICO COMPLETO</p><h1>Tutti i tuoi progressi</h1><div className="progress-score"><div><span>PROGRESS SCORE <small>DEMO</small></span><b>82<em>/100</em></b><p>↑ 10 punti in 4 settimane</p></div><Bars/></div><div className="trend-cards"><div><span>FORZA</span><b>+8,3%</b><small>8 settimane</small></div><div><span>VOLUME</span><b>+12,1%</b><small>8 settimane</small></div><div><span>COSTANZA</span><b>92%</b><small>11/12 workout</small></div></div><History/><h2>Progressi per esercizio</h2>{[['Chest press','+7%','72,5 kg'],['Squat','+11%','112,5 kg'],['Lat machine','+6%','62,5 kg'],['Military press','+4%','42,5 kg'],['Tricipiti ai cavi','+9%','30 kg'],['Bicipiti ai cavi','+5%','25 kg']].map(x=><div className="exercise-progress" key={x[0]}><div><b>{x[0]}</b><small>Miglior carico · {x[2]}</small></div><Spark/><strong>↑ {x[1]}</strong></div>)}</section>}
function Summary({go}:{go:(v:View)=>void}){return <main className="summary-screen"><div className="success">✓</div><p className="eyebrow">ALLENAMENTO COMPLETATO</p><h1>Un altro sì ai tuoi progressi.</h1><p>Hai completato tutti gli esercizi del giorno 2.</p><div className="summary-grid"><div><span>DURATA</span><b>54 min</b></div><div><span>VOLUME</span><b>7.840 kg</b></div><div><span>SERIE</span><b>18/18</b></div><div><span>PR</span><b>2</b></div></div><button className="primary wide" onClick={()=>go('progress')}>Vedi tutti i progressi →</button></main>}
function Bars(){return <div className="bars">{[32,38,44,42,55,61,68,79].map((h,i)=><i key={i} style={{height:h}}/>)}</div>}
function Spark(){return <div className="spark">{[12,20,17,28,25,38,42,50].map((h,i)=><i key={i} style={{height:h/2}}/>)}</div>}
